#ifndef MDLFLDCHARIDS_H
#define MDLFLDCHARIDS_H

#define MDL_FLDCHAR_GET_MAJORID(mdlFldCharId) ((mdlFldCharId) >> 8)
#define MDL_FLDCHAR_GET_MINORID(mdlFldCharId) ((mdlFldCharId) & 0xff)
#define MDL_FLDCHAR_PACKID(major, minor)      (((major) << 8) | ((minor) & 0xff)) // 'major' is the character id

typedef enum
{
    HERO_MDL_FLDCHAR_SCHOOL = MDL_FLDCHAR_PACKID(1, 0),
    HERO_MDL_FLDCHAR_SCHOOL_SUMMER = MDL_FLDCHAR_PACKID(1, 1),
    HERO_MDL_FLDCHAR_DAYOFF = MDL_FLDCHAR_PACKID(1, 2),
    HERO_MDL_FLDCHAR_DAYOFF_SUMMER = MDL_FLDCHAR_PACKID(1, 3),
    HERO_MDL_FLDCHAR_SCHOOL_SEES = MDL_FLDCHAR_PACKID(1, 4),
    HERO_MDL_FLDCHAR_SCHOOL2 = MDL_FLDCHAR_PACKID(1, 5),
    HERO_MDL_FLDCHAR_SWIMSUIT = MDL_FLDCHAR_PACKID(1, 6),
    HERO_MDL_FLDCHAR_TOWEL = MDL_FLDCHAR_PACKID(1, 7),
    HERO_MDL_FLDCHAR_YUKATA = MDL_FLDCHAR_PACKID(1, 8),
} HeroMdlFldChar;

#endif