#ifndef SCRTYPES_H
#define SCRTYPES_H

typedef enum
{
    SCR_STACK_TYPE_INTEGER, // signed short or int
    SCR_STACK_TYPE_FLOAT,
    SCR_STACK_TYPE_ADDR = 4, // Not sure
    SCR_STACK_TYPE_STRING
} ScrStackType;

typedef enum
{
    SCR_CONTENT_TYPE_PROCEDURE,
    SCR_CONTENT_TYPE_LABEL,
    SCR_CONTENT_TYPE_INSTR,
    SCR_CONTENT_TYPE_MSG,
    SCR_CONTENT_TYPE_STRINGS,
    SCR_CONTENT_TYPE_MAX
} ScrContentType;

// TODO
typedef enum
{
    SCR_CODEFUNC_PUSHI,
    SCR_CODEFUNC_PUSHF,
    SCR_CODEFUNC_PUSHIX,
    SCR_CODEFUNC_PUSHIF,
    SCR_CODEFUNC_PUSHREG,
    SCR_CODEFUNC_PROC = 7,
    SCR_CODEFUNC_COMM,
    SCR_CODEFUNC_JMP = 10,
    SCR_CODEFUNC_RUN = 12,
    SCR_CODEFUNC_GOTO,
    SCR_CODEFUNC_ADD,
    SCR_CODEFUNC_SUB,
    SCR_CODEFUNC_MUL,
    SCR_CODEFUNC_DIV,
    SCR_CODEFUNC_EQ = 22,
    SCR_CODEFUNC_NEQ,
    SCR_CODEFUNC_S,
    SCR_CODEFUNC_L,
    SCR_CODEFUNC_SE,
    SCR_CODEFUNC_LE,
    SCR_CODEFUNC_PUSHS = 29,
    SCR_CODEFUNC_PUSHLIX,
    SCR_CODEFUNC_PUSHLFX,
    SCR_CODEFUNC_POPLIX,
    SCR_CODEFUNC_POPLFX,

    SCR_CODEFUNC_MAX = 35
} ScrOpCode;

#endif