#ifndef K_COMMAND_H
#define K_COMMAND_H

#include "Utils.h"

u32 K_Cmd_SKIP_TO_DARK_HOUR();
u32 K_Cmd_REQ_CLND_SKIP();
u32 K_Cmd_FADE_IN();
u32 K_Cmd_FADE_OUT();
u32 K_Cmd_FADE_OUT_SYNC();
u32 K_Cmd_GET_MONTH();
u32 K_Cmd_GET_DAY();
u32 K_Cmd_GET_DAY_OF_WEEK();
u32 K_Cmd_GET_TIME();
u32 K_Cmd_DATE_IN_RANGE();
u32 K_Cmd_RESRC_MDL_ANIM();
u32 K_Cmd_RESRC_MDL_ANIM_SYNC();
u32 K_Cmd_RESRC_MODEL_SCALE();
u32 K_Cmd_GET_DUNGEON_FLOOR();
u32 K_Cmd_CREATE_FLD_MDL();
u32 K_Cmd_CREATE_MDL();
u32 K_Cmd_CREATE_NPC_SYNC();
u32 K_Cmd_RESRC_MDL_SET_COLLIS_RADIUS();
u32 K_Cmd_PLAY_BGM();
u32 K_Cmd_GET_NPC_COUNT();
u32 K_Cmd_CHK_SCENARIO_ANSWER();

#endif