#ifndef ECID_H
#define ECID_H

typedef enum
{
    EC_PRIESTESS = 256,
    EC_EMPRESS,
    EC_EMPEROR,
    EC_HIEROPHANT,
    EC_LOVERS,
    EC_CHARIOT,
    EC_JUSTICE,
    EC_HERMIT,
    EC_CHIDORI,
    EC_FORTUNE,
    EC_STRENGTH,
    EC_TAKAYA,
    EC_JIN,
    EC_HANGEDMAN,
    EC_CHIDORI2,
    EC_JIN2,
    EC_TAKAYA2,
    EC_NYXFOOL,
    EC_NYX_MAGICIAN,
    EC_NYX_PRIESTESS,
    EC_NYX_EMPRESS,
    EC_NYX_EMPEROR,
    EC_NYX_HIEROPHANT,
    EC_NYX_LOVERS,
    EC_NYX_CHARIOT,
    EC_NYX_JUSTICE,
    EC_NYX_HERMIT,
    EC_NYX_FORTUNE,
    EC_NYX_STRENGTH,
    EC_NYX_HANGEDMAN,
    EC_ELIZABETH,
    EC_NYX_DEATH
} EcId;

#endif